# Generated by Django 5.0 on 2024-01-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('shortBio', models.TextField()),
                ('github_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('telegram_link', models.URLField()),
                ('aboutText', models.TextField()),
            ],
        ),
    ]
